-- SEED DATA FOR SENIOR TESTING (3 CLASSES, 30 STUDENTS)
DELETE FROM students;
DELETE FROM classes;
INSERT INTO classes (id, name, type) VALUES ('C_REG_01', 'Lớp Thường 1', 'STANDARD');
INSERT INTO classes (id, name, type) VALUES ('C_REG_02', 'Lớp Thường 2', 'STANDARD');
INSERT INTO classes (id, name, type) VALUES ('C_BIL_01', 'Lớp Song Ngữ 1', 'BILINGUAL');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_01_01', 'Đặng Gia Khanh', 'C_REG_01', 'https://i.pravatar.cc/150?u=S_C_REG_01_01');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_01_02', 'Hoàng Văn Trâm', 'C_REG_01', 'https://i.pravatar.cc/150?u=S_C_REG_01_02');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_01_03', 'Phạm Văn Em', 'C_REG_01', 'https://i.pravatar.cc/150?u=S_C_REG_01_03');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_01_04', 'Phan Minh Nam', 'C_REG_01', 'https://i.pravatar.cc/150?u=S_C_REG_01_04');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_01_05', 'Trần Minh Lợi', 'C_REG_01', 'https://i.pravatar.cc/150?u=S_C_REG_01_05');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_01_06', 'Hoàng Anh Trâm', 'C_REG_01', 'https://i.pravatar.cc/150?u=S_C_REG_01_06');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_01_07', 'Lê Quốc Hòa', 'C_REG_01', 'https://i.pravatar.cc/150?u=S_C_REG_01_07');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_01_08', 'Nguyễn Hải Quân', 'C_REG_01', 'https://i.pravatar.cc/150?u=S_C_REG_01_08');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_01_09', 'Trần Quốc Mai', 'C_REG_01', 'https://i.pravatar.cc/150?u=S_C_REG_01_09');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_01_10', 'Nguyễn Gia Sơn', 'C_REG_01', 'https://i.pravatar.cc/150?u=S_C_REG_01_10');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_02_01', 'Phạm Đức An', 'C_REG_02', 'https://i.pravatar.cc/150?u=S_C_REG_02_01');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_02_02', 'Vũ Quốc Quân', 'C_REG_02', 'https://i.pravatar.cc/150?u=S_C_REG_02_02');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_02_03', 'Bùi Hải Phúc', 'C_REG_02', 'https://i.pravatar.cc/150?u=S_C_REG_02_03');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_02_04', 'Bùi Quốc Mai', 'C_REG_02', 'https://i.pravatar.cc/150?u=S_C_REG_02_04');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_02_05', 'Nguyễn Đức Hòa', 'C_REG_02', 'https://i.pravatar.cc/150?u=S_C_REG_02_05');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_02_06', 'Trần Thị Linh', 'C_REG_02', 'https://i.pravatar.cc/150?u=S_C_REG_02_06');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_02_07', 'Vũ Đức Bình', 'C_REG_02', 'https://i.pravatar.cc/150?u=S_C_REG_02_07');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_02_08', 'Phạm Văn Nam', 'C_REG_02', 'https://i.pravatar.cc/150?u=S_C_REG_02_08');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_02_09', 'Phan Anh Mai', 'C_REG_02', 'https://i.pravatar.cc/150?u=S_C_REG_02_09');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_REG_02_10', 'Nguyễn Minh Lợi', 'C_REG_02', 'https://i.pravatar.cc/150?u=S_C_REG_02_10');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_BIL_01_01', 'Bùi Bảo Linh', 'C_BIL_01', 'https://i.pravatar.cc/150?u=S_C_BIL_01_01');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_BIL_01_02', 'Vũ Trọng Dũng', 'C_BIL_01', 'https://i.pravatar.cc/150?u=S_C_BIL_01_02');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_BIL_01_03', 'Nguyễn Minh Lợi', 'C_BIL_01', 'https://i.pravatar.cc/150?u=S_C_BIL_01_03');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_BIL_01_04', 'Hoàng Văn Vinh', 'C_BIL_01', 'https://i.pravatar.cc/150?u=S_C_BIL_01_04');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_BIL_01_05', 'Hoàng Quốc Trâm', 'C_BIL_01', 'https://i.pravatar.cc/150?u=S_C_BIL_01_05');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_BIL_01_06', 'Đặng Thị Hòa', 'C_BIL_01', 'https://i.pravatar.cc/150?u=S_C_BIL_01_06');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_BIL_01_07', 'Hoàng Thị Lợi', 'C_BIL_01', 'https://i.pravatar.cc/150?u=S_C_BIL_01_07');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_BIL_01_08', 'Bùi Trọng Linh', 'C_BIL_01', 'https://i.pravatar.cc/150?u=S_C_BIL_01_08');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_BIL_01_09', 'Đỗ Thị Quân', 'C_BIL_01', 'https://i.pravatar.cc/150?u=S_C_BIL_01_09');
INSERT INTO students (id, name, class_id, avatar) VALUES ('S_C_BIL_01_10', 'Trần Thị Em', 'C_BIL_01', 'https://i.pravatar.cc/150?u=S_C_BIL_01_10');